<a href="https://colab.research.google.com/github/kamran-hassan/Code-Kong-Assignment/blob/main/numpy_assignment_code_kong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment

## 1. Import numpy 

In [1]:
import numpy as np

## 2. Create an array of 10 zeroes

In [7]:
zero_arr = np.zeros(10)
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3. Create an array of 10 ones

In [9]:
method1 = np.array([1]*10)
print(method1)

method2 = np.ones(10)
print(method2)

[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 4. Create an array of 10 fives

In [10]:
method1 = np.array([5]*10)
print(method1)

method2 = np.full(10,5)
print(method2)

[5 5 5 5 5 5 5 5 5 5]
[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of integers from 11 to 50

In [11]:
x = np.arange(11,50)
print(x)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 6. Create an array of all the even integers from 11 to 50

In [13]:
y = np.arange(12,50,2)
print(y)

[12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


## 7. Create a 3 * 3 matrices of values from range 0 to 8 

In [18]:
z = np.arange(0,9)
z = z.reshape(3,3)
print(z)

# we can also go with resize also
z1 = np.arange(0,9)
z1 = np.resize(z1,(3,3))
print(z1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Use numpy to gentrate a number randomly between 0 and 1

In [27]:
r = np.random.rand()
print(r)

0.0340218146845348


## Create the following matrices

### 20 linrarly spaced points between 0 and 2

In [30]:
l = np.linspace(0,2,20)
print(l)

[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]


## Numpy indexing and selection

In [31]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Use the above matrices for the following set of questions

### 1. only first value of matrice mat

In [33]:
mat[0][0]

1

### 2. middle value of matrice mat

In [36]:
np.median(mat)

13.0

### 3. first two rows and last one column values of matrice mat

In [49]:
print(mat[0:2][:])  # first two row

print((mat[:,4]).reshape(5,1))   # last column i have used reshpe for better visualization it not  compulsory while operation

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 5]
 [10]
 [15]
 [20]
 [25]]


### 4. last row and all column values of matrice mat

In [52]:
print(mat[-1,:])  # last row 

print(mat) #all column mean all complete matrix

[21 22 23 24 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
